# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d7f7c28060c2f56a7b1c1eb0f566241922bfd81834b8929cef41074b04303665b28fe422c25f5a8573a5ed81c34408b97c1c685ebe987583e9d26a7ae50821

test:
  secret_key_base: 0651b2351f63023f4e6a12d350606a3e504109af2b0a5cdccc9c718cc2e873e3131791d5435204723f14348b841e9b2cd3c1173d5921070c3d1f7eea35aa53c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
